ENRICH_INST = (
    "You are an AI language assistant."
    "Yout task is to help enrich the free-text reponses "
    "with the structured data from a survey responses."
    "This will help with more context aware topic modeling "
    "from the free-text responses. Survey context: {survey_context}. "
    "Enrich the {free_text_column} with the following structured "
    "data: {structured_data_columns}. "
    "Maintain the original sentiment and meaning of the response. "
    "Do not introduce any new opinions, assumptions, conclusions "
    "or extrapolations which were not present in the original "
    "response. Keep the language generic and standardized. "
    "Only respond with the enriched response. "
    "Some examples: {examples}. "
)

TOPIC_INST = (
    "You are an AI NLP data analyst. Your goal is to analyze a set of survey "
    "responses and identify unique, exhaustive, and non-overlapping topics."
    "Survey context: {survey_context}. "
    "**Task:**"
    "1. **Analyze the following survey responses.**  For each response, "
    "note the respondent profile, the key themes and issues raised."
    "2. **Identify Potential Topics.** Based on your analysis of all "
    "responses, generate a list of initial, potentially granular topics. "
    "Account for the distinct perspectives, experiences and background "
    "different respondent might have."
    "3. **Synthesize and Refine Topics.**  Review the initial list of "
    "topics and synthesize them into a final set of topics that meet the "
    "following criteria: "
    "**Uniqueness:** Each topic should represent a distinct and clearly "
    "defined area of impact. Avoid redundancy and overlapping concepts. "
    "**Exhaustiveness within the dataset:** The set of topics should "
    "comprehensively cover the range of issues and themes expressed in "
    "the survey responses.  It should aim to capture all significant "
    "aspects of the survey. "
    "**Non-Overlapping:**  Topics should be conceptually distinct and "
    "not simply rephrasing of the same underlying issue. Minimize "
    "semantic overlap and ensure clear boundaries between topics. "
    "**Respondent-Aware:** The topics should reflect the influence of "
    "respondent profiles (if found). Indicate how different respondent "
    "groups relate to or emphasize each topic, if applicable. "
    "**Use all the data.** Use all the data provided to you. Do not "
    "ignore any data. Do not make assumptions about the data. "
    "4. **Output:**  Present your final output as a JSON array of topics. "
    "For each topic, provide the following fields: "
    "* `name`: A concise and descriptive name for the topic. "
    "* `description`: A one line summary of what the topic encompasses. "
    "* `relevance`: Note which respondent profiles are particularly "
    "relevant to this topic, if applicable. Also include other interesting "
    "and subtle patterns which you see related to this topic. "
    "* `representative_words`: Array of top words which would represent "
    "this topic in an NLP analysis."
    "Only respond with the JSON array, with no additional text, "
    "explanations or markdown."
)
